=== GitSetGoRishabh/NIET-Web-Tech-Workshop/HTML/sessional-1/q5.dtd
<!ELEMENT students (student+)>

<!ELEMENT student (rollno, name, email, department)>

<!ELEMENT rollno (#PCDATA)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT email (#PCDATA)>

<!ELEMENT department (CSE | ECE | ME)>

<!ELEMENT CSE (#PCDATA)>
<!ELEMENT ECE (#PCDATA)>
<!ELEMENT ME (#PCDATA)>

=== GitSetGoRishabh/NIET-Web-Tech-Workshop/sessional-1/q5.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE students SYSTEM "q5.dtd">

<students>

    <student>
        <rollno>101</rollno>
        <name>Rishabh Singh Yadav</name>
        <email>rishabh@gmail.com</email>
        <department>CSE</department>
    </student>

    <student>
        <rollno>102</rollno>
        <name>Aman</name>
        <email>aman@gmail.com</email>
        <department>ECE</department>
    </student>

    <student>
        <rollno>103</rollno>
        <name>Rahul</name>
        <email>rahul@gmail.com</email>
        <department>ME</department>
    </student>

</students>
